from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.home, name='home'),
    path('shop/', views.shop, name='shop'),
    path('category/<slug:slug>/', views.category_detail, name='category_detail'),
    path('product/<slug:slug>/', views.product_detail, name='product_detail'),
    path('cart/', views.cart_view, name='cart'),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('update-cart-item/<int:item_id>/', views.update_cart_item, name='update_cart_item'),
    path('remove-from-cart/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('place-order/', views.place_order, name='place_order'),
    path('order-confirmation/<int:order_id>/', views.order_confirmation, name='order_confirmation'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('order/<int:order_id>/', views.order_detail, name='order_detail'),
    # Service Booking URLs
    path('services/', views.services, name='services'),
    path('service/<slug:slug>/', views.service_detail, name='service_detail'),
    path('book-service/<slug:service_slug>/', views.book_service, name='book_service'),
    path('booking-confirmation/<int:booking_id>/', views.booking_confirmation, name='booking_confirmation'),
    path('process-booking-payment/<int:booking_id>/', views.process_booking_payment, name='process_booking_payment'),
    path('my-bookings/', views.my_bookings, name='my_bookings'),
    path('technician-admin/', views.technician_admin_dashboard, name='technician_admin_dashboard'),
    path('create-quotation/<int:booking_id>/', views.create_quotation, name='create_quotation'),
    path('view-quotation/<int:quotation_id>/', views.view_quotation, name='view_quotation'),
    path('update-booking-status/<int:booking_id>/', views.update_booking_status, name='update_booking_status'),
    path('complete-job/<int:booking_id>/', views.complete_job, name='complete_job'),
    path('technician-quotations/', views.technician_quotations, name='technician_quotations'),
    path('edit-quotation/<int:quotation_id>/', views.edit_quotation, name='edit_quotation'),
    path('send-quotation/<int:quotation_id>/', views.send_quotation, name='send_quotation'),
    path('api/booking-details/<int:booking_id>/', views.api_booking_details, name='api_booking_details'),
    path('technician-vehicles/', views.technician_vehicles, name='technician_vehicles'),
    path('vehicle-details/<int:vehicle_id>/', views.vehicle_details, name='vehicle_details'),
    path('add-vehicle-log/<int:vehicle_id>/', views.add_vehicle_log, name='add_vehicle_log'),
    path('technician-profile/', views.technician_profile, name='technician_profile'),
    path('technician-calendar/', views.technician_calendar, name='technician_calendar'),
    path('technician-calendar/<int:year>/<int:month>/', views.technician_calendar, name='technician_calendar_month'),
    path('technician-payments/', views.technician_payments, name='technician_payments'),
    path('technician-sales-report/', views.technician_sales_report, name='technician_sales_report'),
    path('clock-in/', views.clock_in, name='clock_in'),
    path('clock-in/<int:booking_id>/', views.clock_in, name='clock_in_booking'),
    path('clock-out/', views.clock_out, name='clock_out'),
    path('upload-site-image/<int:booking_id>/', views.upload_site_image, name='upload_site_image'),
    path('booking-details/<int:booking_id>/', views.booking_details, name='booking_details'),
    path('print-job-card/<int:booking_id>/', views.print_job_card, name='print_job_card'),
    path('print-invoice/<int:booking_id>/', views.print_invoice, name='print_invoice'),
    # M-Pesa Payment URLs
    path('mpesa/callback/', views.mpesa_callback, name='mpesa_callback'),
    path('mpesa/pay/<int:order_id>/', views.initiate_mpesa_payment, name='initiate_mpesa_payment'),
    # Receipt and Invoice URLs
    path('receipt/<int:order_id>/', views.download_receipt, name='download_receipt'),
    path('invoice/<int:order_id>/', views.download_invoice, name='download_invoice'),
    path('booking-receipt/<int:booking_id>/', views.download_booking_receipt, name='download_booking_receipt'),
] 