# Generated by Django 5.2.1 on 2025-05-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address_line2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='alt_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alternative Address'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='alt_address_line2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alternative Address Line 2'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='alt_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alternative City'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='alt_country',
            field=models.CharField(blank=True, default='Kenya', max_length=100, null=True, verbose_name='Alternative Country'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='alt_postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Alternative Postal Code'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='alt_state_province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alternative State/Province'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='card_expiry',
            field=models.CharField(blank=True, help_text='MM/YYYY format', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='card_last_four',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='card_type',
            field=models.CharField(blank=True, choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, default='Kenya', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mpesa_phone',
            field=models.CharField(blank=True, help_text='Phone number registered with M-Pesa', max_length=20, null=True, verbose_name='M-Pesa Phone Number'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_currency',
            field=models.CharField(choices=[('KES', 'Kenyan Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='KES', max_length=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='receive_newsletter',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state_province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
