# Generated by Django 5.0.7 on 2026-08-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_advertisement_newsletter_video_featuredproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='brands')),
                ('description', models.TextField(blank=True)),
                ('link_url', models.URLField(blank=True, help_text='URL to link to when clicked', null=True)),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for accessibility', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers display first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
