# Generated by Django 5.0.7 on 2026-08-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('hero', 'Hero Slider'), ('advert', 'Advertisement Bar'), ('promo', 'Promotional Banner'), ('category', 'Category Banner'), ('bestseller', 'Bestseller Banner')], default='hero', max_length=20),
        ),
    ]
