# Generated by Django 5.0.7 on 2026-08-12 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_banner_banner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Optional: Link to specific category for category-specific banners', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='store.category'),
        ),
    ]
