# Generated by Django 5.0.7 on 2026-08-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_herosection_alter_brand_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceHeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Slide title/headline', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Subtitle or description text', max_length=300)),
                ('image', models.ImageField(help_text='Hero slide image', upload_to='service_hero_slides')),
                ('link_url', models.URLField(blank=True, help_text='Optional URL to link to when clicked', null=True)),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for accessibility', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers display first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Hero Slide',
                'verbose_name_plural': 'Service Hero Slides',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='HeroImage',
        ),
        migrations.DeleteModel(
            name='HeroSection',
        ),
    ]
