# Generated by Django 5.0.7 on 2026-08-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_serviceheroslide_delete_heroimage_delete_herosection'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceheroslide',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description based on the image content'),
        ),
    ]
