# Generated by Django 5.0.7 on 2026-08-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_serviceheroslide_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='callout_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Additional callout fee for service visits', max_digits=10),
        ),
    ]
