# Generated by Django 5.0.7 on 2026-08-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_booking_payment_amount_booking_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AddField(
            model_name='brand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alt text for accessibility', max_length=200),
        ),
        migrations.AlterField(
            model_name='brand',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Lower numbers display first'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='link_url',
            field=models.URLField(blank=True, help_text='URL to link to when clicked', null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(upload_to='brands'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
