# Generated by Django 5.0.7 on 2026-08-13 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_brand_options_brand_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (e.g., 15 for 15%) or fixed amount', max_digits=10)),
                ('applies_to', models.CharField(choices=[('all_products', 'All Products'), ('specific_products', 'Specific Products'), ('categories', 'Categories')], default='all_products', max_length=20)),
                ('start_date', models.DateTimeField(help_text='When this discount becomes active')),
                ('end_date', models.DateTimeField(help_text='When this discount expires')),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum purchase amount to qualify', max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount', max_digits=10, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Total number of times this discount can be used', null=True)),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times this discount has been used')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='discounts', to='store.category')),
                ('products', models.ManyToManyField(blank=True, related_name='discounts', to='store.product')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Discount percentage (e.g., 30 for 30% off)', max_digits=5)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('max_quantity_per_customer', models.PositiveIntegerField(default=1, help_text='Max quantity each customer can purchase')),
                ('total_stock_limit', models.PositiveIntegerField(blank=True, help_text='Total stock available for this sale', null=True)),
                ('sold_count', models.PositiveIntegerField(default=0, help_text='Number of items sold')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(related_name='flash_sales', to='store.product')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('offer_type', models.CharField(choices=[('buy_x_get_y', 'Buy X Get Y Free'), ('bundle', 'Bundle Deal'), ('free_shipping', 'Free Shipping'), ('gift_with_purchase', 'Gift with Purchase'), ('tiered_discount', 'Tiered Discount')], max_length=30)),
                ('buy_quantity', models.PositiveIntegerField(blank=True, help_text='Quantity to buy (for Buy X Get Y)', null=True)),
                ('get_quantity', models.PositiveIntegerField(blank=True, help_text='Quantity to get free (for Buy X Get Y)', null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage for bundle/tiered deals', max_digits=5, null=True)),
                ('min_purchase_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='offers', to='store.category')),
                ('gift_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_offers', to='store.product')),
                ('products', models.ManyToManyField(blank=True, related_name='offers', to='store.product')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
