# Generated by Django 5.0.7 on 2026-08-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_discount_flashsale_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Mustek East Africa', max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='Upload your site logo', null=True, upload_to='site_settings')),
                ('favicon', models.ImageField(blank=True, help_text='Upload your site favicon', null=True, upload_to='site_settings')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=500, null=True)),
                ('footer_background_color', models.CharField(default='#000000', help_text='Hex color code (e.g., #000000)', max_length=7)),
                ('footer_heading_color', models.CharField(default='#d4af37', help_text='Hex color code (e.g., #d4af37)', max_length=7)),
                ('default_currency', models.CharField(default='KES', max_length=3)),
                ('business_hours', models.TextField(blank=True, help_text='e.g., Mon-Fri: 9AM-5PM, Sat: 10AM-2PM', null=True)),
                ('google_analytics_id', models.CharField(blank=True, help_text='Google Analytics tracking ID', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
