# Generated by Django 5.0.7 on 2026-08-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_background_color',
            field=models.CharField(default='#333333', help_text='Hex color code (e.g., #333333)', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_heading_color',
            field=models.CharField(default='#ffffff', help_text='Hex color code (e.g., #ffffff)', max_length=7),
        ),
    ]
