# Generated by Django 5.0.7 on 2026-08-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_sitesettings_footer_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number with country code (e.g., 254700000000)', max_length=20, null=True),
        ),
    ]
