# Generated by Django 5.0.7 on 2026-08-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_sitesettings_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_about_text',
            field=models.TextField(blank=True, default='Premium outdoor and camping equipment for all your adventures. Quality products for every outdoor experience.', help_text='About text in footer', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_message_1',
            field=models.CharField(blank=True, default='Orders ship next day', help_text='First message in top bar', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_message_2',
            field=models.CharField(blank=True, default='Logistics info updates within 1-2 working days', help_text='Second message in top bar', max_length=200, null=True),
        ),
    ]
