# Generated by Django 5.0.7 on 2026-08-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_sitesettings_footer_about_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='background_color',
            field=models.CharField(default='#ff0000', help_text='Background color for flash sale popup (hex code)', max_length=7),
        ),
        migrations.AddField(
            model_name='flashsale',
            name='background_color',
            field=models.CharField(default='#ff0000', help_text='Background color for flash sale popup (hex code)', max_length=7),
        ),
    ]
