# Generated by Django 5.0.7 on 2026-08-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_advertisement_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='enable_promo_popup',
            field=models.BooleanField(default=False, help_text='Enable promotional popup on site'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='promo_background_color',
            field=models.CharField(default='#000000', help_text='Background color for promotional popup (hex code)', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='promo_button_color',
            field=models.CharField(default='#dc3545', help_text='Button color for promotional popup (hex code)', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='promo_button_text',
            field=models.CharField(blank=True, default='SHOP NOW', help_text='Button text for promotional popup', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='promo_message',
            field=models.TextField(blank=True, default='Buy any 2 camping items and get 15% OFF automatically at checkout!', help_text='Promotional popup message', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='promo_title',
            field=models.CharField(blank=True, default='EXCLUSIVE ONLINE DEAL', help_text='Promotional popup title', max_length=200, null=True),
        ),
    ]
