# Generated by Django 5.0.7 on 2026-08-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_sitesettings_enable_promo_popup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='description',
            field=models.TextField(blank=True, help_text='Description text for banner content (especially for bestseller banners)'),
        ),
    ]
