# Generated by Django 5.0.7 on 2026-08-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_banner_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='description',
            field=models.TextField(blank=True, help_text='Description text for advertisement content'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='background_color',
            field=models.CharField(default='#ff0000', help_text='Background color for advertisement panel (hex code)', max_length=7),
        ),
    ]
