# Generated by Django 5.0.7 on 2026-08-13 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_advertisement_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Company Profile', 'verbose_name_plural': 'Company Profile'},
        ),
        migrations.AddField(
            model_name='technician',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='promo_background_color',
            field=models.CharField(choices=[('#000000', 'Black'), ('#1a1a1a', 'Dark Gray'), ('#2c3e50', 'Dark Blue'), ('#34495e', 'Navy'), ('#8e44ad', 'Purple'), ('#2980b9', 'Blue'), ('#27ae60', 'Green'), ('#e67e22', 'Orange'), ('#c0392b', 'Red'), ('#ffffff', 'White'), ('#f8f9fa', 'Light Gray')], default='#000000', help_text='Background color for promotional popup', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='promo_button_color',
            field=models.CharField(choices=[('#dc3545', 'Red'), ('#c0392b', 'Dark Red'), ('#e74c3c', 'Light Red'), ('#007bff', 'Blue'), ('#17a2b8', 'Cyan'), ('#28a745', 'Green'), ('#ffc107', 'Yellow'), ('#fd7e14', 'Orange'), ('#6f42c1', 'Purple'), ('#343a40', 'Dark Gray'), ('#ffffff', 'White')], default='#dc3545', help_text='Button color for promotional popup', max_length=7),
        ),
        migrations.CreateModel(
            name='ClockInLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in_time', models.DateTimeField()),
                ('clock_out_time', models.DateTimeField(blank=True, null=True)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clock_in_logs', to='store.booking')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clock_in_logs', to='store.technician')),
            ],
            options={
                'ordering': ('-date', '-clock_in_time'),
            },
        ),
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='site_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_images', to='store.booking')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
    ]
