# Generated by Django 5.0.7 on 2026-08-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_sitesettings_options_technician_total_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='default_from_email',
            field=models.EmailField(blank=True, help_text='Default sender email address', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_backend',
            field=models.CharField(default='django.core.mail.backends.smtp.EmailBackend', help_text='Email backend to use', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_host',
            field=models.CharField(blank=True, help_text='SMTP server hostname (e.g., smtp.gmail.com)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_host_password',
            field=models.CharField(blank=True, help_text='SMTP password', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_host_user',
            field=models.CharField(blank=True, help_text='SMTP username (usually email address)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_port',
            field=models.PositiveIntegerField(blank=True, help_text='SMTP server port (e.g., 587 for TLS, 465 for SSL)', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_use_tls',
            field=models.BooleanField(default=True, help_text='Use TLS for email sending'),
        ),
    ]
