# Generated by Django 5.0.7 on 2026-08-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_sitesettings_default_from_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='has_admin_access',
            field=models.BooleanField(default=False, help_text='Grant this technician access to the Django admin panel'),
        ),
    ]
