# Generated by Django 5.0.7 on 2026-08-13 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_technician_has_admin_access'),
    ]

    operations = [
    ]
